services:
  yvesrocher_feed_handler:
    environment:
      - TZ=Europe/Moscow
    image: imediadev/yvesrocher_feed_handler
    user: "1002:1002"
    env_file: .env
    volumes:
      - ./logs:/app/logs
      - ./${FEEDS_FOLDER}:/app/${FEEDS_FOLDER}
      - /home/main_ftp_user/projects/yvesrocher/${NEW_FEEDS_FOLDER}:/app/${NEW_FEEDS_FOLDER}
      - ./${IMAGE_FOLDER}:/app/${IMAGE_FOLDER}
      - /home/main_ftp_user/projects/yvesrocher/${NEW_IMAGE_FOLDER}:/app/${NEW_IMAGE_FOLDER}
